# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u0413\u0430\u0440\u0447\u0438\u0433')),
                ('body', models.TextField()),
                ('author', models.CharField(max_length=50, verbose_name='\u041d\u0438\u0439\u0442\u043b\u044d\u0433\u0447')),
            ],
        ),
    ]
